---

## Without updating this, docker fails to start
- name: "update device-mapper"
  yum: name=device-mapper state=latest

- name: "install docker"
  yum: name="https://get.docker.com/rpm/1.7.1/centos-7/RPMS/x86_64/docker-engine-1.7.1-1.el7.centos.x86_64.rpm" state=present
  notify: "restart docker"
